### ISSUE TITLE
Extract Logger Trace Util

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#575] opened 2018-10-17 04:58 UTC
https://github.com/poetapp/node/blob/master/src/StorageWriter/ClaimController.ts#L38-L42
```ts
private readonly log = (level: LogTypes) => (message: string) => async (value: any) => {
    const logger = this.logger
    logger[level]({ value }, message)
    return value
  }
```

**Comment by lautarodragan** [comment] 2019-04-04 05:11
Duplicate of https://github.com/poetapp/node/issues/702

**Closed by lautarodragan** 2019-04-04 05:11 UTC
Labels: refactor
